make delayBetweenMeasurementsMs configurable
wirenboard/wb-mqtt-adc pull request #21
Opened 2021-09-03 11:42 UTC by webconn

Closes #18 

Patched-by: cu6apum (https://github.com/cu6apum)
Reviewed-by: Nikita Maslov <nikita.maslov@wirenboard.ru>

2021-09-03 12:09 UTC, KraPete requested changes

2021-09-03 12:09 UTC, KraPete commented on src/sysfs_adc.h
> +        uint32_t DelayBetweenMeasurementsmS = 10;
У нас же С++, не надо хранить периоды в uint32_t и писать размерность в названии. Надо при чтении конфига сконвертировать в `std::chrono::millisecond` и везде его использовать.

2021-09-03 12:09 UTC, KraPete commented on src/sysfs_adc.h
> +    uint32_t GetInterval() const;
Тут тоже надо `std::chrono::millisecond`

2021-09-03 12:09 UTC, KraPete commented on debian/changelog
> +  * Add configurable delayBetweenMeasurementsMs (patch provided by cu6apum)
Тут надо написать про название параметра в конфиге, а не в исходниках.

2021-09-03 12:09 UTC, KraPete commented on data/wb-mqtt-adc.schema.json
> +        "poll_interval": {
Это надо ещё в README.md описать.

2021-09-08 04:19 UTC, KraPete commented
Назови иначе. Ещё есть существенная задержка при публикации каждого канала (от 20мс и выше).

2021-09-08 09:44 UTC, webconn commented
В общем, я не удержался и всё переделал, #22

2021-09-08 09:44 UTC, closed without merging